### ISSUE TITLE
rename  to StaticBitArrays.jl

### ISSUE THREAD

**Issue by rafaqz** [chelate/StaticBitArrays.jl#2]
To get this registered it will need the `.jl` suffix and probably the abbreviated S will get flagged as a problem. It's nice to just spell out the "Static" part so everyone knows what this is.

**Comment by chelate** [comment]
Yep, realized this after I got everything up and running.

**Comment by chelate** [comment]
I guess I have to rename all the modules and everything consistently as well.

**Comment by rafaqz** [comment]
And the name here needs the .jl ending ;)

**Comment by chelate** [comment]
My first GitHub issue. Not _too_ hard.

**Comment by chelate** [comment]
Oh man I still need to fix the project file.  Is that a pkg command?  harder than I thought.

**Comment by rafaqz** [comment]
This is hilarious. Did you get it sorted?

**Comment by chelate** [comment]
yeah lol considered burning everything and copying the code into a new package.
